name: Test GH action commit and push

# Configure Manual Trigger
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to push changes'
        required: true
        default: 'test-push'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.inputs.branch }}
    - name: Write uuid to file
      run: |
        UUID=$(cat /proc/sys/kernel/random/uuid)
        echo "uuid: $UUID" > random.txt
    - name: Commit and push changes
      uses: arcezd/github-app-commit-action@v1
      with:
        github-app-private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}
        repository: ${{ github.repository }}
        branch: ${{ github.event.inputs.branch }}
        force-push: true
